# check=skip=SecretsUsedInArgOrEnv
FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

ARG UPSTASH_REDIS_REST_TOKEN
ARG UPSTASH_REDIS_REST_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_KEY
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG STRIPE_SECRET_KEY
ARG RESEND_API_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

RUN echo "UPSTASH_REDIS_REST_TOKEN: $UPSTASH_REDIS_REST_TOKEN"
RUN echo "UPSTASH_REDIS_REST_URL: $UPSTASH_REDIS_REST_URL"
RUN echo "NEXT_PUBLIC_SUPABASE_URL: $NEXT_PUBLIC_SUPABASE_URL"
RUN echo "NEXT_PUBLIC_SUPABASE_KEY: $NEXT_PUBLIC_SUPABASE_KEY"
RUN echo "NEXT_PUBLIC_POSTHOG_KEY: $NEXT_PUBLIC_POSTHOG_KEY"
RUN echo "NEXT_PUBLIC_POSTHOG_HOST: $NEXT_PUBLIC_POSTHOG_HOST"
RUN echo "STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY"
RUN echo "RESEND_API_KEY: $RESEND_API_KEY"
RUN echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: $NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"

ENV UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
ENV UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_KEY=$NEXT_PUBLIC_SUPABASE_KEY
ENV NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"] 