import type { Metadata } from 'next'
import '@/src/globals.css'
import { PostHogProvider } from '@/src/lib/providers'
import ThemeWrapper from '@/src/lib/components/theme-wrapper'
import NavbarWrapper from './navbar-wrapper'

export const metadata: Metadata = {
  title: 'Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <PostHogProvider>
          <ThemeWrapper>
            <NavbarWrapper />
            {children}
          </ThemeWrapper>
        </PostHogProvider>
      </body>
    </html>
  )
}
