name: Build Docker Image

on:
  push:
    branches: 
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    environment: Production

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install minimal dependencies for migrations
        run: npm install drizzle-kit dotenv postgres
      
      - name: Generate Drizzle migrations
        run: npx drizzle-kit generate
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
      
      - name: Run Drizzle migrations
        run: npx drizzle-kit migrate
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_KEY }}
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
            UPSTASH_REDIS_REST_URL=${{ vars.UPSTASH_REDIS_REST_URL }}
            NEXT_PUBLIC_POSTHOG_KEY=${{ vars.NEXT_PUBLIC_POSTHOG_KEY }}
            NEXT_PUBLIC_POSTHOG_HOST=${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}